import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-screen grid grid-cols-1 sm:grid-cols-2">
        <div
          className="h-screen hidden sm:block bg-cover bg-center"
          style={{
            backgroundImage: "url('https://source.unsplash.com/random')",
          }}
        ></div>
        <div className="h-screen w-full flex items-center justify-center">
          <div className="flex flex-col w-10/12 mx-auto ">
            <p className="">Bienvenido de nuevo!</p>
            <h1 className=" text-4xl font-bold">Nos alegra que vuelvas!</h1>

            <input
              className="input-label block mt-6"
              placeholder="Correo"
              type={"text"}
            />
            <input
              className="input-label block mt-4"
              placeholder="Contraseña"
              type={"password"}
            />
            <a className="link">Recuperar contraseña</a>

            <Link href={"/user"}>
              <button className="btn mt-5">Entrar</button>
            </Link>
          </div>
        </div>
      </div>
    </>
  );
}
