-- MySQL Script generated by MySQL Workbench
-- Mon Mar 14 21:30:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- DATABASE mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- DATABASE Interfectorem-Eros-Zebrands
-- -----------------------------------------------------

-- -----------------------------------------------------
-- DATABASE Interfectorem-Eros-Zebrands
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `Interfectorem-Eros-Zebrands` DEFAULT CHARACTER SET utf8 ;
USE `Interfectorem-Eros-Zebrands` ;

-- -----------------------------------------------------
-- Table `Interfectorem-Eros-Zebrands`.`chapter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Interfectorem-Eros-Zebrands`.`chapter` (
  `id_chapter` INT NOT NULL AUTO_INCREMENT,
  `nombre_chapter` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion_chapter` VARCHAR(255) NULL DEFAULT NULL,
  `cantidad_empleados` INT NULL DEFAULT NULL,
  `matriz` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_chapter`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Interfectorem-Eros-Zebrands`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Interfectorem-Eros-Zebrands`.`empleado` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido_paterno` VARCHAR(45) NULL DEFAULT NULL,
  `apellido_materno` VARCHAR(45) NULL DEFAULT NULL,
  `nivel_general` DECIMAL(65,1) NULL DEFAULT NULL,
  `nivel_craft` DECIMAL(65,1) NULL DEFAULT NULL,
  `nivel_business` DECIMAL(65,1) NULL DEFAULT NULL,
  `nivel_people` DECIMAL(65,1) NULL DEFAULT NULL,
  `correo_electronico` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(100) NULL DEFAULT NULL,
  `equipo` VARCHAR(45) NULL DEFAULT NULL,
  `id_chapter` INT NOT NULL,
  `imagen_perfil` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_empleado`),
  INDEX `id_chapter_idx` (`id_chapter` ASC),
  CONSTRAINT `id_chapter_empleado`
    FOREIGN KEY (`id_chapter`)
    REFERENCES `Interfectorem-Eros-Zebrands`.`chapter` (`id_chapter`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Interfectorem-Eros-Zebrands`.`asignacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Interfectorem-Eros-Zebrands`.`asignacion` (
  `id_empleado_member` INT NOT NULL,
  `id_empleado_assistant` INT NOT NULL,
  `fecha_asignacion` DATE NOT NULL,
  PRIMARY KEY (`id_empleado_member`, `id_empleado_assistant`, `fecha_asignacion`),
  INDEX `id_empleado_assistant_idx` (`id_empleado_assistant` ASC),
  CONSTRAINT `id_empleado_assistant`
    FOREIGN KEY (`id_empleado_assistant`)
    REFERENCES `Interfectorem-Eros-Zebrands`.`empleado` (`id_empleado`),
  CONSTRAINT `id_empleado_member`
    FOREIGN KEY (`id_empleado_member`)
    REFERENCES `Interfectorem-Eros-Zebrands`.`empleado` (`id_empleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Interfectorem-Eros-Zebrands`.`periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Interfectorem-Eros-Zebrands`.`periodo` (
  `id_periodo` INT NOT NULL AUTO_INCREMENT,
  `nombre_periodo` VARCHAR(45) NULL,
  `fecha_inicio` DATE NULL DEFAULT NULL,
  `fecha_fin` DATE NULL DEFAULT NULL,
  `estatus_periodo` VARCHAR(45) NULL DEFAULT NULL,
  `id_chapter` INT NOT NULL,
  PRIMARY KEY (`id_periodo`),
  INDEX `id_chapter_idx` (`id_chapter` ASC),
  CONSTRAINT `id_chapter_periodo`
    FOREIGN KEY (`id_chapter`)
    REFERENCES `Interfectorem-Eros-Zebrands`.`chapter` (`id_chapter`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Interfectorem-Eros-Zebrands`.`chaptermood`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Interfectorem-Eros-Zebrands`.`chaptermood` (
  `id_chaptermood` INT NOT NULL AUTO_INCREMENT,
  `puntaje_mood` INT NULL DEFAULT NULL,
  `status_mood` TINYINT NULL DEFAULT NULL,
  `id_periodo` INT NOT NULL,
  `id_empleado` INT NOT NULL,
  PRIMARY KEY (`id_chaptermood`),
  INDEX `id_periodo_idx` (`id_periodo` ASC),
  INDEX `id_empleado_idx` (`id_empleado` ASC),
  CONSTRAINT `id_empleado_mood`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `Interfectorem-Eros-Zebrands`.`empleado` (`id_empleado`),
  CONSTRAINT `id_periodo_mood`
    FOREIGN KEY (`id_periodo`)
    REFERENCES `Interfectorem-Eros-Zebrands`.`periodo` (`id_periodo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Interfectorem-Eros-Zebrands`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Interfectorem-Eros-Zebrands`.`feedback` (
  `id_feedback` INT NOT NULL AUTO_INCREMENT,
  `calificacion_craft` DECIMAL(65,1) NULL DEFAULT NULL,
  `calificacion_personal` DECIMAL(65,1) NULL DEFAULT NULL,
  `calificacion_business` DECIMAL(65,1) NULL DEFAULT NULL,
  `calificacion_promedio` DECIMAL(65,1) NULL DEFAULT NULL,
  `comentario_craft` VARCHAR(255) NULL DEFAULT NULL,
  `comentario_personal` VARCHAR(255) NULL DEFAULT NULL,
  `comentario_business` VARCHAR(255) NULL DEFAULT NULL,
  `comentario_general` VARCHAR(255) NULL DEFAULT NULL,
  `id_empleado_member` INT NOT NULL,
  `id_empleado_assistant` INT NOT NULL,
  PRIMARY KEY (`id_feedback`),
  INDEX `id_empleado_assistant_idx` (`id_empleado_assistant` ASC),
  INDEX `id_empleado_member_idx` (`id_empleado_member` ASC),
  CONSTRAINT `id_empleado_assistant_feedback`
    FOREIGN KEY (`id_empleado_assistant`)
    REFERENCES `Interfectorem-Eros-Zebrands`.`asignacion` (`id_empleado_assistant`),
  CONSTRAINT `id_empleado_member_feedback`
    FOREIGN KEY (`id_empleado_member`)
    REFERENCES `Interfectorem-Eros-Zebrands`.`asignacion` (`id_empleado_member`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Interfectorem-Eros-Zebrands`.`evaluacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Interfectorem-Eros-Zebrands`.`evaluacion` (
  `id_empleado_evaluador` INT NOT NULL,
  `id_empleado_evaluado` INT NOT NULL,
  `id_periodo` INT NOT NULL,
  `id_feedback` INT NOT NULL,
  `nivel_contestan` VARCHAR(45) NULL,
  `estatus` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_realizacion` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_empleado_evaluador`, `id_empleado_evaluado`, `id_periodo`),
  INDEX `id_empleado_evaluado_idx` (`id_empleado_evaluado` ASC),
  INDEX `id_periodo_idx` (`id_periodo` ASC),
  INDEX `id_feedback_idx` (`id_feedback` ASC),
  CONSTRAINT `id_empleado_evaluado`
    FOREIGN KEY (`id_empleado_evaluado`)
    REFERENCES `Interfectorem-Eros-Zebrands`.`empleado` (`id_empleado`),
  CONSTRAINT `id_empleado_evaluador`
    FOREIGN KEY (`id_empleado_evaluador`)
    REFERENCES `Interfectorem-Eros-Zebrands`.`empleado` (`id_empleado`),
  CONSTRAINT `id_feedback_contestan`
    FOREIGN KEY (`id_feedback`)
    REFERENCES `Interfectorem-Eros-Zebrands`.`feedback` (`id_feedback`),
  CONSTRAINT `id_periodo_contestan`
    FOREIGN KEY (`id_periodo`)
    REFERENCES `Interfectorem-Eros-Zebrands`.`periodo` (`id_periodo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Interfectorem-Eros-Zebrands`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Interfectorem-Eros-Zebrands`.`rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion_rol` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Interfectorem-Eros-Zebrands`.`empleado_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Interfectorem-Eros-Zebrands`.`empleado_rol` (
  `id_empleado` INT NOT NULL,
  `id_rol` INT NOT NULL,
  `fecha_rol` DATE NOT NULL,
  PRIMARY KEY (`id_empleado`, `id_rol`, `fecha_rol`),
  INDEX `id_rol_idx` (`id_rol` ASC),
  CONSTRAINT `id_empleado_rol`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `Interfectorem-Eros-Zebrands`.`empleado` (`id_empleado`),
  CONSTRAINT `id_rol_empleado`
    FOREIGN KEY (`id_rol`)
    REFERENCES `Interfectorem-Eros-Zebrands`.`rol` (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Interfectorem-Eros-Zebrands`.`funcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Interfectorem-Eros-Zebrands`.`funcion` (
  `id_funcion` INT NOT NULL AUTO_INCREMENT,
  `nombre_funcion` VARCHAR(255) NULL DEFAULT NULL,
  `descripcion_funcion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_funcion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Interfectorem-Eros-Zebrands`.`banco_preguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Interfectorem-Eros-Zebrands`.`banco_preguntas` (
  `id_pregunta` INT NOT NULL AUTO_INCREMENT,
  `pregunta` VARCHAR(255) NULL DEFAULT NULL,
  `index_pregunta` INT NULL DEFAULT NULL,
  `nivel_pregunta` DECIMAL(65,1) NULL DEFAULT NULL,
  `dimension_craft` VARCHAR(45) NULL DEFAULT NULL,
  `dimension_personal` VARCHAR(45) NULL DEFAULT NULL,
  `dimension_business` VARCHAR(45) NULL DEFAULT NULL,
  `tipo_pregunta` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pregunta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Interfectorem-Eros-Zebrands`.`respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Interfectorem-Eros-Zebrands`.`respuesta` (
  `id_respuesta` INT NOT NULL AUTO_INCREMENT,
  `pregunta` VARCHAR(255) NULL DEFAULT NULL,
  `descripcion_respuesta` VARCHAR(255) NOT NULL,
  `tipo_respuesta` VARCHAR(45) NULL DEFAULT NULL,
  `index_respuesta` INT NULL DEFAULT NULL,
  `id_empleado_evaluador` INT NOT NULL,
  `id_empleado_evaluado` INT NOT NULL,
  PRIMARY KEY (`id_respuesta`),
  INDEX `id_empleado_evaluado_idx` (`id_empleado_evaluado` ASC),
  INDEX `id_empleado_evaluador_idx` (`id_empleado_evaluador` ASC),
  CONSTRAINT `id_empleado_evaluado_respuesta`
    FOREIGN KEY (`id_empleado_evaluado`)
    REFERENCES `Interfectorem-Eros-Zebrands`.`evaluacion` (`id_empleado_evaluado`),
  CONSTRAINT `id_empleado_evaluador_respuesta`
    FOREIGN KEY (`id_empleado_evaluador`)
    REFERENCES `Interfectorem-Eros-Zebrands`.`evaluacion` (`id_empleado_evaluador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Interfectorem-Eros-Zebrands`.`rol_funciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Interfectorem-Eros-Zebrands`.`rol_funciones` (
  `id_rol` INT NOT NULL,
  `id_funcion` INT NOT NULL,
  PRIMARY KEY (`id_rol`, `id_funcion`),
  INDEX `id_funcion_idx` (`id_funcion` ASC),
  CONSTRAINT `id_funcion_rol`
    FOREIGN KEY (`id_funcion`)
    REFERENCES `Interfectorem-Eros-Zebrands`.`funcion` (`id_funcion`),
  CONSTRAINT `id_rol_funcion`
    FOREIGN KEY (`id_rol`)
    REFERENCES `Interfectorem-Eros-Zebrands`.`rol` (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;